services:
  db:
    image: postgres:15.8-alpine
    container_name: medshift_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: medshift_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "15432:5432"
    networks:
      - medshift_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d medshift_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: medshift_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "16379:6379"
    networks:
      - medshift_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: medshift_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: info@trident.software
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15433:80"
    networks:
      - medshift_network
    depends_on:
      - db
    restart: unless-stopped
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:

networks:
  medshift_network:
    driver: bridge