# Generated by Django 5.0.10 on 2025-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Street name and number",
                        max_length=255,
                        verbose_name="street address",
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, suite, unit, building, floor, etc. (optional)",
                        max_length=255,
                        verbose_name="address line 2",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="postal code"),
                ),
                (
                    "state_province",
                    models.CharField(
                        blank=True,
                        help_text="Administrative level 1: State/Province/Canton code (e.g., VD, QC, NY)",
                        max_length=100,
                        verbose_name="state/province/canton",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("CH", "Switzerland"),
                            ("CA", "Canada"),
                            ("LU", "Luxembourg"),
                            ("MC", "Monaco"),
                        ],
                        default="CH",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude coordinate for map display",
                        max_digits=9,
                        null=True,
                        verbose_name="latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude coordinate for map display",
                        max_digits=9,
                        null=True,
                        verbose_name="longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "address",
                "verbose_name_plural": "addresses",
                "ordering": ["country", "city", "address"],
                "indexes": [
                    models.Index(
                        fields=["country", "city"],
                        name="core_addres_country_46bfbe_idx",
                    ),
                    models.Index(
                        fields=["postal_code"], name="core_addres_postal__e6c232_idx"
                    ),
                ],
            },
        ),
    ]
