# Generated by Django 5.0.10 on 2025-10-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="location",
            field=models.ForeignKey(
                default=2,
                help_text="Primary work location for this employee",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="employees.location",
                verbose_name="location",
            ),
            preserve_default=False,
        ),
    ]
