# Generated by Django 5.0.10 on 2025-10-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_employee_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="effective_from",
            field=models.DateField(
                blank=True,
                help_text="Date when department became operational",
                null=True,
                verbose_name="effective from",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="effective_to",
            field=models.DateField(
                blank=True,
                help_text="Date when department ceased operations",
                null=True,
                verbose_name="effective to",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="location_notes",
            field=models.TextField(
                blank=True,
                help_text="Physical location details within facility",
                verbose_name="location notes",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="phone_extension",
            field=models.CharField(
                blank=True,
                help_text="Internal phone extension",
                max_length=10,
                verbose_name="phone extension",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed department description",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this department is currently operational",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for this department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="department manager",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text="Full department name",
                max_length=100,
                unique=True,
                verbose_name="department name",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="employees_d_code_c27ed6_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="employees_d_is_acti_97e269_idx"
            ),
        ),
    ]
