# Generated by Django 5.0.10 on 2025-10-25 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "employees",
            "0004_department_effective_from_department_effective_to_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ["name"],
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.RemoveIndex(
            model_name="location",
            name="employees_l_name_c3e022_idx",
        ),
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short code for location (e.g., GVA, LAU, BRN)",
                max_length=20,
                verbose_name="location code",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(
                help_text="Street address", max_length=255, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                help_text="City name", max_length=100, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                choices=[("CA", "Canada"), ("CH", "Switzerland")],
                default="CH",
                help_text="Country code",
                max_length=2,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Main email address for this location",
                max_length=254,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this location is currently operational",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="labor_budget",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Budget for labor costs per month in Swiss Francs",
                max_digits=10,
                verbose_name="monthly labor budget (CHF)",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS latitude coordinate (optional)",
                max_digits=9,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="GPS longitude coordinate (optional)",
                max_digits=9,
                null=True,
                verbose_name="longitude",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="User responsible for this location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_locations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="location manager",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Full location name",
                max_length=100,
                unique=True,
                verbose_name="location name",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about this location",
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Main phone number for this location",
                max_length=20,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="postal_code",
            field=models.CharField(
                help_text="Postal/ZIP code", max_length=20, verbose_name="postal code"
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed position description",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this position is currently in use",
                verbose_name="is active",
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="title",
            field=models.CharField(
                help_text="Full position title",
                max_length=100,
                unique=True,
                verbose_name="position title",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["code"], name="employees_l_code_1e586e_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["city"], name="employees_l_city_8f89e6_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["code"], name="employees_p_code_ed4725_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["is_active"], name="employees_p_is_acti_a6b3eb_idx"
            ),
        ),
    ]
