# Generated by Django 5.0.10 on 2025-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0006_populate_location_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(
                help_text="Short code for location (e.g., GVA, LAU, BRN)",
                max_length=20,
                unique=True,
                verbose_name="location code",
            ),
        ),
    ]
