# Generated by Django 5.0.10 on 2025-10-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0007_make_location_code_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                choices=[
                    ("CA", "Canada"),
                    ("CH", "Switzerland"),
                    ("LU", "Luxembourg"),
                    ("MC", "Monaco"),
                ],
                default="CH",
                help_text="Country code",
                max_length=2,
                verbose_name="country",
            ),
        ),
    ]
