# Generated by Django 5.0.10 on 2025-10-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0008_add_luxembourg_monaco_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Apartment, suite, unit, building, floor, etc. (optional)",
                max_length=255,
                verbose_name="address line 2",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="state_province",
            field=models.CharField(
                blank=True,
                help_text="Administrative level 1: State/Province/Canton code (e.g., VD, QC, NY)",
                max_length=100,
                verbose_name="state/province/canton",
            ),
        ),
    ]
