# Generated by Django 5.0.10 on 2025-10-25 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("employees", "0009_add_address_line2_and_state_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="Location address details",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="core.address",
                verbose_name="address",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Street address (deprecated - use address_detail)",
                max_length=255,
                verbose_name="address",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                help_text="Apartment, suite, unit, building, floor, etc. (deprecated)",
                max_length=255,
                verbose_name="address line 2",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City name (deprecated - use address_detail)",
                max_length=100,
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CA", "Canada"),
                    ("CH", "Switzerland"),
                    ("LU", "Luxembourg"),
                    ("MC", "Monaco"),
                ],
                default="CH",
                help_text="Country code (deprecated - use address_detail)",
                max_length=2,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Postal/ZIP code (deprecated - use address_detail)",
                max_length=20,
                verbose_name="postal code",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="state_province",
            field=models.CharField(
                blank=True,
                help_text="Administrative level 1 (deprecated - use address_detail)",
                max_length=100,
                verbose_name="state/province/canton",
            ),
        ),
    ]
