# Generated by Django 5.0.10 on 2025-10-25 17:25

from django.db import migrations


def migrate_location_addresses_forward(apps, schema_editor):
    """
    Create Address records from existing Location address fields.
    """
    Location = apps.get_model('employees', 'Location')
    Address = apps.get_model('core', 'Address')

    for location in Location.objects.all():
        # Create Address record with data from Location
        address = Address.objects.create(
            address=location.address or '',
            address_line_2=location.address_line_2 or '',
            city=location.city or '',
            postal_code=location.postal_code or '',
            state_province=location.state_province or '',
            country=location.country or 'CH',
            latitude=location.latitude,
            longitude=location.longitude,
        )

        # Link Location to new Address
        location.address_detail = address
        location.save(update_fields=['address_detail'])

        print(f"Migrated address for location: {location.name}")


def migrate_location_addresses_backward(apps, schema_editor):
    """
    Reverse migration - copy data back from Address to Location fields.
    """
    Location = apps.get_model('employees', 'Location')

    for location in Location.objects.filter(address_detail__isnull=False):
        addr = location.address_detail

        # Copy data back to old fields
        location.address = addr.address
        location.address_line_2 = addr.address_line_2
        location.city = addr.city
        location.postal_code = addr.postal_code
        location.state_province = addr.state_province
        location.country = addr.country
        location.latitude = addr.latitude
        location.longitude = addr.longitude
        location.save()

        # Delete Address record
        addr.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0010_add_address_detail_to_location"),
        ("core", "0001_initial"),  # Ensure Address model exists
    ]

    operations = [
        migrations.RunPython(
            migrate_location_addresses_forward,
            reverse_code=migrate_location_addresses_backward
        ),
    ]
