# Generated by Django 5.0.10 on 2025-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0011_migrate_location_addresses_to_address_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="location",
            name="notes",
        ),
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional information and notes about the employee",
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Additional information and notes about this location",
                verbose_name="description",
            ),
        ),
    ]
