# Generated by Django 5.0.10 on 2025-10-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0003_employee_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Start Date & Time"),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="End Date & Time")),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Duration of unpaid break in minutes",
                        verbose_name="Break Duration (minutes)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for this shift",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty for open shifts",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="employees.employee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="employees.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="employees.position",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift",
                "verbose_name_plural": "Shifts",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted_by_employee", "Accepted by Employee"),
                            ("rejected_by_employee", "Rejected by Employee"),
                            ("approved", "Approved by Manager"),
                            ("rejected", "Rejected by Manager"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "request_message",
                    models.TextField(
                        blank=True,
                        help_text="Message from requesting employee",
                        verbose_name="Request Message",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True,
                        help_text="Response from target employee or manager",
                        verbose_name="Response Message",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Approved At"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_swaps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved By",
                    ),
                ),
                (
                    "original_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_as_original",
                        to="schedules.shift",
                        verbose_name="Original Shift",
                    ),
                ),
                (
                    "requesting_employee",
                    models.ForeignKey(
                        help_text="Employee who wants to swap their shift",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_swap_requests",
                        to="employees.employee",
                        verbose_name="Requesting Employee",
                    ),
                ),
                (
                    "target_employee",
                    models.ForeignKey(
                        help_text="Employee who is asked to take the shift",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_swap_requests",
                        to="employees.employee",
                        verbose_name="Target Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Swap Request",
                "verbose_name_plural": "Shift Swap Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Template Name"),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Time only, without date", verbose_name="Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="Time only, without date", verbose_name="End Time"
                    ),
                ),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Break Duration (minutes)"
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        default=list,
                        help_text="List of weekday numbers: 0=Monday, 6=Sunday",
                        verbose_name="Days of Week",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="employees.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_templates",
                        to="employees.position",
                        verbose_name="Position",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Template",
                "verbose_name_plural": "Shift Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Unavailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Start Date & Time"),
                ),
                ("end_datetime", models.DateTimeField(verbose_name="End Date & Time")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick Leave"),
                            ("personal", "Personal"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Reason",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a recurring unavailability?",
                        verbose_name="Recurring",
                    ),
                ),
                (
                    "recurrence_pattern",
                    models.JSONField(
                        blank=True,
                        help_text="JSON pattern for recurring unavailability (e.g., every Monday)",
                        null=True,
                        verbose_name="Recurrence Pattern",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unavailabilities",
                        to="employees.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unavailability",
                "verbose_name_plural": "Unavailabilities",
                "ordering": ["-start_datetime"],
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["start_datetime", "end_datetime"],
                name="schedules_s_start_d_382f29_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["location", "start_datetime"],
                name="schedules_s_locatio_d27539_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["employee", "start_datetime"],
                name="schedules_s_employe_0b0788_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(fields=["status"], name="schedules_s_status_833793_idx"),
        ),
        migrations.AddIndex(
            model_name="unavailability",
            index=models.Index(
                fields=["employee", "start_datetime"],
                name="schedules_u_employe_be48e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unavailability",
            index=models.Index(
                fields=["start_datetime", "end_datetime"],
                name="schedules_u_start_d_c03f24_idx",
            ),
        ),
    ]
